
version: "3.8"

services:
  approval-be:
    build:
      context: ./apps/approver-be
      dockerfile: Dockerfile
    container_name: approver_be
    restart: unless-stopped
    environment:
      - HTTP_PORT=8080
    env_file:
      - ./apps/approver-be/.env
    volumes:
      - ./apps/approver-be:/var/www/html
    ports:
      - "3014:8080"
    networks:
      - approver-internal
    depends_on:
      - appextract

  approval-fe:
    build:
      context: ./apps/approver-fe
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://approval-be:8080
    container_name: approver_fe
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://approval-be:8080
    env_file:
      - ./apps/approver-fe/.env.local
    ports:
      - "8097:3000"
    networks:
      - approver-internal
    depends_on:
      - approval-be

  appextract:
    build:
      context: ./apps/appextract
      dockerfile: Dockerfile
    container_name: approver_python
    restart: unless-stopped
    volumes:
      - ./apps/appextract:/app
    ports:
      - "8280:8000"
    networks:
      - approver-internal

networks:
  approver-internal:
    driver: bridge
